# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ralvarezdev/decrypter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ralvarezdev/decrypter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bralvarezdev/decrypter.proto\x12\x0bralvarezdev\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x11ListFilesResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t\"&\n\x12\x44\x65\x63ryptFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"H\n\x13\x44\x65\x63ryptFileResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x1b\n\x13\x63\x65rtificate_content\x18\x02 \x01(\x0c\x32\xa4\x01\n\tDecrypter\x12\x43\n\tListFiles\x12\x16.google.protobuf.Empty\x1a\x1e.ralvarezdev.ListFilesResponse\x12R\n\x0b\x44\x65\x63ryptFile\x12\x1f.ralvarezdev.DecryptFileRequest\x1a .ralvarezdev.DecryptFileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ralvarezdev.decrypter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTFILESRESPONSE']._serialized_start=73
  _globals['_LISTFILESRESPONSE']._serialized_end=111
  _globals['_DECRYPTFILEREQUEST']._serialized_start=113
  _globals['_DECRYPTFILEREQUEST']._serialized_end=151
  _globals['_DECRYPTFILERESPONSE']._serialized_start=153
  _globals['_DECRYPTFILERESPONSE']._serialized_end=225
  _globals['_DECRYPTER']._serialized_start=228
  _globals['_DECRYPTER']._serialized_end=392
# @@protoc_insertion_point(module_scope)
